-- SUPERSEDED — do not run this file (it's the one that errored with
-- "relation subteams does not exist"). Round 264 dropped the `subteams`
-- table entirely, making this moot either way.
--
-- Run sql/pending/add-round264-consolidated-subteam-migration.sql
-- instead.
