-- Round 324 — backfill for the `labels` table from the team's LABEL
-- reference CSV ("TRACKING_FULL_CATALOG_0809 - LABEL"), per explicit
-- request ("the LABEL file has the back fill for label ... let's do some
-- import"). Cannot be run against the live database from here (no
-- credentials) — review before running, especially the match report this
-- header describes, then run in Supabase's SQL editor. Idempotent: safe
-- to run more than once (every write is a COALESCE-guarded backfill of a
-- currently-empty field, never an overwrite of existing data).
--
-- What this does, in order:
--   1. Adds `labels.parent_label` (new column — stores the CSV's "LABEL
--      CHÍNH" parent/main-label name for SUB-LABEL rows; no prior column
--      existed for this relationship).
--   2. Backfills, for every label whose name matches a CSV row:
--        - default_lbl_tag  (only if currently NULL — a release's own LBL
--          tag and any value someone already set here always wins; see
--          lib/releaseTags.js's resolveLblTag and add-round320).
--        - parent_label     (only if currently NULL).
--        - hop_tac          (only if currently NULL or empty array — never
--          drops an existing hợp tác selection someone already made in the
--          app).
--
-- Matching: the CSV's "Label" column carries ad-hoc bracket notes this
-- app's own data doesn't use (e.g. "[END_CONTRACT]Minh Nguyen",
-- "[ENDCONTRACT] Minh Nguyen", "[END CONTRACT] TTQTENT Music" — 3
-- different spellings of the same tag seen in the source). Those bracket
-- prefixes are stripped before matching, and matched against
-- labels.label_name in BOTH its plain form and this app's own unrelated
-- "HĐ - " unsigned-contract prefix (lib/labelHelpers.js's LABEL_PREFIX)
-- — see the `import_data` CTE below and its two OR'd join conditions.
-- This is a best-effort NAME match with no live database to verify
-- against — run the "unmatched rows" SELECT immediately below FIRST and
-- check its output before trusting the UPDATE actually reached everyone
-- you expect.
--
-- Loại label -> LBL_ tag code mapping used (1:1, all 12 LBL_ codes incl.
-- the new LBL_ARTIST added alongside this for the CSV's ARTIST rows —
-- see lib/releaseTags.js):
--   ARTIST->LBL_ARTIST, SONGWRITER->LBL_SONGWRITER, PRODUCER->LBL_PRODUCER,
--   RECORD_LABEL->LBL_RECORD_LABEL, ARTIST_MANAGEMENT->LBL_ARTIST_MANAGEMENT,
--   MUSIC_COMPANY->LBL_MUSIC_COMPANY, RIGHTS_ACQUIRER->LBL_RIGHTS_ACQUIRER,
--   MEDIA_ORG->LBL_MEDIA_ORG, RESELLER->LBL_RESELLER, INTERNAL->LBL_INTERNAL,
--   SUB-LABEL->LBL_SUB-LABEL, END_CONTRACT->LBL_END_CONTRACT.
--
-- HỢP TÁC -> labels.hop_tac mapping used (per explicit decision):
--   NS->"Nhạc Số", YTB->"Youtube", PUB->"Publishing". The CSV's own
--   "END_CONTRACT" value inside this column is deliberately NOT mapped
--   into hop_tac — it's redundant with the separate "Loại label" column
--   already carrying that value for the same rows (-> LBL_END_CONTRACT).
--
-- Excluded from import (per explicit decision / source-data judgment):
--   - the CSV's own "Phân Loại" column (done/recheck) — this is the
--     SOURCE sheet's internal QC/review-status tracking, not this app's
--     labels.phan_loai field (Priority/New/Collab before) — different
--     vocabulary, different meaning, left alone.
--   - the CSV's trailing "Tổng cộng" (Total) summary row.
--   - contract_signed / Hợp Đồng status — not part of this backfill;
--     that field has its own real workflow (send HĐ -> ticket -> done)
--     already live in the app, not something to stamp from a static CSV.
--
-- Row-count note: the CSV has 568 data rows (Tổng cộng excluded); after
-- collapsing 6 duplicate-name groups (bracket-prefix variants of
-- the same underlying label — see merge policy in the round's chat log:
-- the more informative row wins, a bare END_CONTRACT-only duplicate with
-- no other data loses), this backfills up to 562 distinct label names.
-- Not every one will find a match in the live `labels` table — that's
-- expected and fine; unmatched CSV rows are simply skipped (no new label
-- rows are ever created by this script, only existing ones backfilled).

alter table labels add column if not exists parent_label text;

-- Run this FIRST and review: every CSV label name that does NOT match an
-- existing labels.label_name (plain or "HĐ - "-prefixed). Expected to be
-- non-empty — the CSV covers labels going back further than what's been
-- created in the app, and spelling can differ beyond the bracket-prefix
-- cases already normalized here.
with import_data(csv_name, lbl_tag, parent_label, hop_tac) as (
  values
  ('VN Music', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('ANS / BEAT CHAT LUONG CAO', 'LBL_SUB-LABEL', 'TD NETWORK', ARRAY[]::text[]),
  ('Minh Nguyen', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('CT Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('PTMEDIA', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Relaxing Live Music', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('VieEnt / Âm Nhạc Số', 'LBL_SUB-LABEL', 'ANS Music and Entertainment', ARRAY[]::text[]),
  ('ANS Music and Entertainment', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('G5R', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('BeeBoss', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('VIEENT Music', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('NGUYỄN VĂN CHUNG', 'LBL_SONGWRITER', NULL, ARRAY[]::text[]),
  ('Bang Kieu', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Ân Thiên Vỹ', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('BDMedia', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('TimmyDzi Media', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('WM Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('TQVN Music', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('KOSEM', 'LBL_MEDIA_ORG', NULL, ARRAY[]::text[]),
  ('BM MUSIC GROUP', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Exclusive Music', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('System Recordings', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Trí Tô Media', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('H2O Music', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('HL Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('Dino Recording', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('ICM Entertainment', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('RIN Media', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('TTM MUSIC', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('VieEnt|Âm Nhạc Số', 'LBL_SUB-LABEL', 'ANS Music and Entertainment', ARRAY[]::text[]),
  ('HTM Entertainment', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('One Way Recording', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('TienTienMusic', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('QN Entertainment', 'LBL_PRODUCER', NULL, ARRAY[]::text[]),
  ('Vọng Cổ Việt Nam', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('NVC MEDIA', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('TimmyDzi - MultimediaMaitrise/MusicMastered', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('TG MEDIA', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('H2O Lofi', 'LBL_SUB-LABEL', 'CT Media', ARRAY[]::text[]),
  ('TTQTENT Music', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('TD Network', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('MC NGUYÊN KHANG', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('PACE RECORD', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('H2O Houselak', 'LBL_SUB-LABEL', 'CT Media', ARRAY[]::text[]),
  ('CONG TY HTD', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Kiyoshi Phan', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Ngụy Minh Khang Entertainment', 'LBL_MEDIA_ORG', NULL, ARRAY[]::text[]),
  ('Qinn Media', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Ca sỹ Minh Thu', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('AI Media Solutions', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('H2O Vinahouse', 'LBL_SUB-LABEL', 'CT Media', ARRAY[]::text[]),
  ('G5R Remix', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Trang Music Productions', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('20X Entertainment', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('HHD MUSIC', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('AN NHIEN MEDIA', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('1988s Entertainment', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('Woohox', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('Thanh Âm Chiến Sĩ', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Tracy Thảo My', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Tố My', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Nguyen Tan Studio', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Tùng', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('VIR MUSIC', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Nguyễn Duy Khiêm', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('BMT Music', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Vic Media', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Ngọc Ký singer', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('H2O EDM', 'LBL_SUB-LABEL', 'CT Media', ARRAY[]::text[]),
  ('BT2K Production', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('Thanh Ngọc', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('M''Acoustic Studio', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('Tố Đen', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('The Ghost Legacy', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Thịnh Suy', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Opalus24 Records', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('TH ACADEMY', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Nhạc sỹ Quốc An', 'LBL_SONGWRITER', NULL, ARRAY[]::text[]),
  ('Mii Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('84 MIX', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('BOM Music Group', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('9C Media', 'LBL_RECORD_LABEL', NULL, ARRAY['Youtube']::text[]),
  ('ProductionQ', 'LBL_MEDIA_ORG', NULL, ARRAY[]::text[]),
  ('KOY Music Group', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Gin Tuan Kiet', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('TH Media', 'LBL_RIGHTS_ACQUIRER', NULL, ARRAY[]::text[]),
  ('LY Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('Danh Tuấn Trung', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Leo Music', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Hoàng Rapper', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Bix Music Group', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Dunghoangpham', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Ducth Entertainment', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('93NEWG Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('V2T Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('Gia Đình Lớn', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY[]::text[]),
  ('ECM Squad', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('Nhạc sĩ Giáng Sol', 'LBL_SONGWRITER', NULL, ARRAY[]::text[]),
  ('Ngoc Phung', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('YuniBoo', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Luny Entertainment', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('Anna Yến Phượng', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Nguyễn Bá Hùng', 'LBL_SONGWRITER', NULL, ARRAY[]::text[]),
  ('DIMZ', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Hồ Khắc Tùng', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('HOÀNG OANH', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('GABI Network', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Tiến Nguyễn', 'LBL_SONGWRITER', NULL, ARRAY[]::text[]),
  ('MTRI Prod', 'LBL_PRODUCER', NULL, ARRAY[]::text[]),
  ('Chú Gián Nhỏ', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Youth Music Team', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Tú GG', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('T.Bynz / T Entertainment', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Tóc Tiên', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nguyễn Hữu Liệu', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nhạc Sĩ Phan Long', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('NguyenThuong', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('NT Music', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Diệu Kiên', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('OrchidD', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('NS Nguyễn Phi Hùng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ngô Lan Hương', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Đăng Official', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('LBD Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ben Eagle', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('Pham Hong Bien', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Đình Nguyễn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phan Như Thuỳ', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Le Van Entertainment', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('BIBO Entertainment', 'LBL_PRODUCER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lương Quý Tuấn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('HAPPY BIRTHDAY - TIMMYDZI', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thanh Duy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('SIDUS AND TEU', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('LÊ THU THẢO', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('H2O Ballad', 'LBL_SUB-LABEL', 'CT Media', ARRAY['Nhạc Số']::text[]),
  ('Bconcept Entertainment', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Pin Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('ATOM', 'LBL_PRODUCER', NULL, ARRAY['Nhạc Số']::text[]),
  ('AMY MUSIC', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tấn Tài Entertainment', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('TAN Entertainment', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Beta Music', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('ALIEN.NEXT.DOOR', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Zuongzero Ent', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('UNDERSOUTHERN', 'LBL_RIGHTS_ACQUIRER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phương Mai', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lê Thiện Hiếu', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Dung Hoàng Phạm', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lê Chí Trung', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Vưu Tuấn Kiệt /KIEY', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Saka Trương Tuyền', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lê Thành Trung', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('HANA CẨM TIÊN', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Archived', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('1967 Entertainment', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phạm Thu Hà', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Củ Cải', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('The United Saigon Orchestra', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Brother A', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('LQ MEDIA', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Khả Hiệp Official', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Keyo', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Anna Trâm', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('VietEnt / Âm Nhạc Số', 'LBL_SUB-LABEL', 'ANS Music and Entertainment', ARRAY['Nhạc Số']::text[]),
  ('RayO', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('meChill', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hạo Thiên', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hải Gokume', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('THE GENUINE RECORD', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Xám', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nam Việt - Nhạc Pro', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('BM Music', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('BÌN', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Overline Vietnam', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ngô Quang Dũng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Gia Huy Singer', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tuki Team', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Thái Hoàng', 'LBL_PRODUCER', NULL, ARRAY['Nhạc Số']::text[]),
  ('NSUT Thanh Hằng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('HT PRODUCTIONS', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Châu Dương', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('BIG Records', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Wood Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hồng Quân WyTy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('HỘI', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('NH Music Group', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('VNStudiomusic', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Son Mach', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Satch999', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('RebelSaint Records', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phong Max', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hồ Quang Hiếu', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Đình Dũng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Express Music', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('VT Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Seveni Records', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ngô Hồng Quang', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Jay Đào', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('HUVA Music', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thiên Ca', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Quang Dung', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nguyễn Thuý Hà (Nguyên Hà)', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('MAD Production', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Dizzy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Dani D', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Võ Lê Mi', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Meow Label', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Đại Thành', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Cố NSUT QUÝ BÌNH', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Triệu Hồng Ngọc', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thái Chi', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Star Melody', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Mai Tien Dung', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Mega Gs', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Luân', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hivane', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Cộng Hưởng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trung Ngon', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Elbi Original', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('TRANG CHUYÊN OFFICIAL', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Theanh28', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('OG Entertainment', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số','Youtube','Publishing']::text[]),
  ('Như Ngọc', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ngô Lan Hương - Exclusively Licensed to VIEENT', 'LBL_SUB-LABEL', 'Ngô Lan Hương', ARRAY['Nhạc Số']::text[]),
  ('Lê Xuân Nghi', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Khỉ Con Music', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('KC Media', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hữu Công', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Finn Nguyên Hy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('WM Records', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Vũ Hữu Minh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Út Nhị Mino', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tiến Tới Music', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('ROBI', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('PhuongThao', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('PHỤNG QUỐC GIANG', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nguyên Trung', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('ĐÀO NGỌC SANG', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('CHANGMIE', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('BMKTCR', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('AnhVu Music', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Zang', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Mivi Diễm Anh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hào JK', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Đặng Khánh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Duy Hải', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('2!MUCH', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('VŨ PHƯƠNG', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tuệ Phương', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trương Trần Anh Duy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trần Hoài Thy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('SOHASG Sound', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('Shen Music', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ngọc Xuyên', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('N.', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Kem Baby', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hauxenz', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Cwhite', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('135Band', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('TK Records', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('THE EIGHT ENTERTAINMENT', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thảo Phạm', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tân Nhàn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Oliu', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('NH4T Music', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Linh Lor', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Đinh Đại Vũ', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Duuyen', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Do Music', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Win Entertainment', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('VPS', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Vera Madsen', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('UniFLOWs Label', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tuyết Mai', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trương Diễm', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thái Hưng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Synz K', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Reyvin', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('QUÁCH PHÚ THÀNH', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ngô Thái Bảo', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Longg', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('La Hồng Đức', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Jee Trần', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('INZ Entertainment', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Học Sinh Cá Biệt', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('DouMs', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ái Phương', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trọng Nhân', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thiên Dũng', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Quach Tuan Du', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phát Huy T4', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('OGB GANGZ', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Now Or Later', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Non Khăn Rằn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lisa Thùy Lâm', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('La Zung', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Khánh Cường', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Di Di', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Cộng Em', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Célyn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Bùi Vĩnh Phúc', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoài My', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Vết Xước', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trần Ngọc Hân', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thành Sơn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nguyễn Minh Xuân Ái', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Mee Media', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Marse', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lê Vũ Official', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('JBEE7', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hunter V Entertainment', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Y Nhung', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hải Linh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('GLG', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Dreamwork', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('DJ KIM CHOL', 'LBL_PRODUCER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Choco Trúc Phương', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Bình Gold', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('30 Pictures', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('WM20', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('VNDMC', 'LBL_RIGHTS_ACQUIRER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Việt Sơn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('ThiSax', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('The Mars Party', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thắng Rừng Media', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Poorboy', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phát Hồ', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('NHV Entertainment', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nhạc sĩ Nguyễn Thanh Lộc', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Khánh Linh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Cao Trung Hiếu', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Bùi Dương Thái Hà', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('KOY Records', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Đinh Tú', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Vũ Sam', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Võ Minh Lâm', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tuyết Ngân', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thiên Minh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Teddy Tran', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('tạo mới nè122', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('SA', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nguyễn Vĩ', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('NamDuc Official', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Meme Media', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Kim Trọng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('KIỀU THƠ MELLOW', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Kenjumboy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Huy Diệc', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Huấn Hoa Hồng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('HS Talent', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Thiên Đỉnh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Ngọc Sơn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Kaylee', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('h0n', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Gia Linh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('EEZO', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('DIỆU VÂN', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('DG Team', 'LBL_PRODUCER', NULL, ARRAY['Nhạc Số']::text[]),
  ('DAQUIN', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Chuchu', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Anfang', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('9NOTE RECORDS', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Win G', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Wanbi Tuấn Anh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('VINHTRAN', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Vicky Nhung', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trương Thảo Nhi', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('The SGM Label', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('The 199x', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Rich Khwam', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Pickle Sun', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phú Hunter', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('OCEANS Music Group', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nhạc Sĩ Võ Hiếu', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nhã', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nguyễn Hoàng Phúc', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nathan Lee', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('MUSICTAB', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('MTB Media', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('MINGJI', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('KxK', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('KProx', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ken Trần', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('JAYEO', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Jannc', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('HepiHepi', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('HChun', 'LBL_PRODUCER', NULL, ARRAY['Nhạc Số']::text[]),
  ('GreenD', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Gia Huy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Đỗ Thụy Khanh', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Chí Thiện', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Candy Juice Music', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ca sĩ Phúc Anh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Bin Yet', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('AREA70', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Yoon Nguyên', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('William Music Group', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('VieEnt on behalf of Lemese and Fillinus', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('VGEE', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trương Khải Minh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trini Trinh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trần Việt Dương', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thanh Hưng', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tân Test', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('SynthEX Records', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('STG Music', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Starry Night', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('SoundGanG', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('SONICK OFFICIAL', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Sinl', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Say You Do', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('RIO SUN', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Revir Quang Hà', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Quang Music', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phùng Ngọc Huy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phạm Thu Trang Official', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phạm Thanh Sang', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phạm Quỳnh Như', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nhóm nhạc SOLPA', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('NHÂN DẠNG', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nhạc Sĩ Duy Cường', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ngân Nara', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('N.O.M', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('My Everything', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('MSV Group', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('Moz Entertainment', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('Mai Yến Chi', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lục Huy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Long Ngô', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('⁠LIÊU VINH PHÚ - FU', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Khong Anh Music', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Khải Nguyễn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Jesse JP', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Huy Nam', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hồ Phong An', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Homie On Da Mic', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Lan', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hannie', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('H-Kray', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Finn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Đức Thoa', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('ĐẠT MAX', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('DinhLong', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Diêu Ngọc Bích Trâm', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Dấu Vân Tay', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Cao Sĩ Hùng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('BMD', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('BLUEBELLS STUDIOS', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('Barry Nam Bảo', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Bảo Trân Gemini official', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('B:OKEH', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Astronaut Music Group', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Aplus84', 'LBL_RIGHTS_ACQUIRER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Anh Quân Idol', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Akira Phan', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Air Media', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tấn Thành', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Noisy Boy', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Yeah1', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('X2X Entertainment', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('WowU Media', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('Woni', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Vũ Anh Thư', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('VNDJM', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('VIOLIXX', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Vĩnh Thích Ăn Ngon', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('VieEnt on behalf of Quách Tuấn Du', 'LBL_SUB-LABEL', 'Quach Tuan Du', ARRAY['Nhạc Số']::text[]),
  ('VieEnt on behalf of Nguyên', 'LBL_SUB-LABEL', 'NGUYÊN', ARRAY['Nhạc Số']::text[]),
  ('Vạch Kẻ Đường', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tukie', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('TUDUCA', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tú Tri', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trường Anh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trịnh Thiên Ân', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trí Vũ', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tô Đạt', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('TiTi', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thiên Long', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('THE.B', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('TAP Music', 'LBL_PRODUCER', NULL, ARRAY['Nhạc Số']::text[]),
  ('SSay Huỳnh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Shine By Sai', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('SG CO.OP', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('Sea Media', 'LBL_PRODUCER', NULL, ARRAY['Nhạc Số']::text[]),
  ('RPT NASTEE', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Rion Trung Hiếu', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ra-Hbie', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('QuocDat', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Poll Official', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Pittu Quyên', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phan Lê Hà My', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phạm Thuỳ Linh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phạm Thiêng Ngân', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Pha Lê', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('ODDS.TONES Records', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nio Tuấn Dũng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nien', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('NH4T', 'LBL_PRODUCER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nguyễn Kiều Oanh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nguyễn Cảnh Luân', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('NGUYÊN', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Neam', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nam Lê', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nam Anh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Một Con Đường Hai Ngã Rẽ', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('MINA THANH TÂM', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Mikayni', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('M - NGUYỄN VĂN NAM', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lightin', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lê Quốc Anh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lâm Thành Vinh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('LÂM SUNG', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Láo Soái Nhi', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('LANY S', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Kim Thành Lộc', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Khang Ki', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Khả Ngân', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Javon', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Integral Silence', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('ICG Media', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('I''m In Love', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Huyền Anh Yoko', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Huy Bui', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hùng Min', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hồ Đá Chà Gươm', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Hải Dương', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Hạc', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Henry Ngọc Thạch', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Heni', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hải Nam', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('GRAMMY MUSIC VIET NAM', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('GABI Music', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Đường Hưng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Đào Mác', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Duy B', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Drum7', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('dotted.', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Dihoa Media', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Denis Dang', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('DAT', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Dablo Anh Dũng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('CRIIO', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Công Ty Hùng Hoàng - Huỳnh Quốc Huy', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Chủ Quán Hội', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Châu Dương - Exclusively Licensed to VIEENT', 'LBL_SUB-LABEL', 'Châu Dương', ARRAY['Nhạc Số']::text[]),
  ('Cá Mây', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Bull', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Bùi Thế Bảo Official', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Big Dreams Label', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('BI BẢO', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Bee9 Offical', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('ASC', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Annie Thai', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('ALIEN.NEXT.DOOR - EXCLUSIVE LICENSED TO VIEENT', 'LBL_SUB-LABEL', 'ALIEN.NEXT.DOOR', ARRAY['Nhạc Số']::text[]),
  ('ACV Entertainment', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('ACB Pictures', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('A.N PRODUCTIONS', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('4thằngngu', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('2kTraDa', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Soul Music Worldwide', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  (':B', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[])
)
select d.csv_name
from import_data d
where not exists (
  select 1 from labels l
  where l.label_name = d.csv_name or l.label_name = 'HĐ - ' || d.csv_name
)
order by d.csv_name;

-- The actual backfill. COALESCE-guarded on every column — never
-- overwrites a value that's already set.
with import_data(csv_name, lbl_tag, parent_label, hop_tac) as (
  values
  ('VN Music', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('ANS / BEAT CHAT LUONG CAO', 'LBL_SUB-LABEL', 'TD NETWORK', ARRAY[]::text[]),
  ('Minh Nguyen', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('CT Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('PTMEDIA', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Relaxing Live Music', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('VieEnt / Âm Nhạc Số', 'LBL_SUB-LABEL', 'ANS Music and Entertainment', ARRAY[]::text[]),
  ('ANS Music and Entertainment', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('G5R', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('BeeBoss', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('VIEENT Music', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('NGUYỄN VĂN CHUNG', 'LBL_SONGWRITER', NULL, ARRAY[]::text[]),
  ('Bang Kieu', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Ân Thiên Vỹ', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('BDMedia', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('TimmyDzi Media', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('WM Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('TQVN Music', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('KOSEM', 'LBL_MEDIA_ORG', NULL, ARRAY[]::text[]),
  ('BM MUSIC GROUP', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Exclusive Music', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('System Recordings', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Trí Tô Media', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('H2O Music', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('HL Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('Dino Recording', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('ICM Entertainment', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('RIN Media', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('TTM MUSIC', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('VieEnt|Âm Nhạc Số', 'LBL_SUB-LABEL', 'ANS Music and Entertainment', ARRAY[]::text[]),
  ('HTM Entertainment', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('One Way Recording', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('TienTienMusic', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('QN Entertainment', 'LBL_PRODUCER', NULL, ARRAY[]::text[]),
  ('Vọng Cổ Việt Nam', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('NVC MEDIA', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('TimmyDzi - MultimediaMaitrise/MusicMastered', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('TG MEDIA', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('H2O Lofi', 'LBL_SUB-LABEL', 'CT Media', ARRAY[]::text[]),
  ('TTQTENT Music', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('TD Network', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('MC NGUYÊN KHANG', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('PACE RECORD', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('H2O Houselak', 'LBL_SUB-LABEL', 'CT Media', ARRAY[]::text[]),
  ('CONG TY HTD', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Kiyoshi Phan', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Ngụy Minh Khang Entertainment', 'LBL_MEDIA_ORG', NULL, ARRAY[]::text[]),
  ('Qinn Media', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Ca sỹ Minh Thu', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('AI Media Solutions', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('H2O Vinahouse', 'LBL_SUB-LABEL', 'CT Media', ARRAY[]::text[]),
  ('G5R Remix', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Trang Music Productions', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('20X Entertainment', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('HHD MUSIC', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('AN NHIEN MEDIA', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('1988s Entertainment', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('Woohox', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('Thanh Âm Chiến Sĩ', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Tracy Thảo My', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Tố My', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Nguyen Tan Studio', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Tùng', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('VIR MUSIC', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Nguyễn Duy Khiêm', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('BMT Music', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Vic Media', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Ngọc Ký singer', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('H2O EDM', 'LBL_SUB-LABEL', 'CT Media', ARRAY[]::text[]),
  ('BT2K Production', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('Thanh Ngọc', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('M''Acoustic Studio', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('Tố Đen', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('The Ghost Legacy', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Thịnh Suy', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Opalus24 Records', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('TH ACADEMY', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Nhạc sỹ Quốc An', 'LBL_SONGWRITER', NULL, ARRAY[]::text[]),
  ('Mii Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('84 MIX', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('BOM Music Group', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('9C Media', 'LBL_RECORD_LABEL', NULL, ARRAY['Youtube']::text[]),
  ('ProductionQ', 'LBL_MEDIA_ORG', NULL, ARRAY[]::text[]),
  ('KOY Music Group', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Gin Tuan Kiet', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('TH Media', 'LBL_RIGHTS_ACQUIRER', NULL, ARRAY[]::text[]),
  ('LY Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('Danh Tuấn Trung', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Leo Music', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Hoàng Rapper', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Bix Music Group', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Dunghoangpham', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Ducth Entertainment', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('93NEWG Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('V2T Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('Gia Đình Lớn', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY[]::text[]),
  ('ECM Squad', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('Nhạc sĩ Giáng Sol', 'LBL_SONGWRITER', NULL, ARRAY[]::text[]),
  ('Ngoc Phung', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('YuniBoo', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Luny Entertainment', 'LBL_MUSIC_COMPANY', NULL, ARRAY[]::text[]),
  ('Anna Yến Phượng', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Nguyễn Bá Hùng', 'LBL_SONGWRITER', NULL, ARRAY[]::text[]),
  ('DIMZ', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Hồ Khắc Tùng', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('HOÀNG OANH', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('GABI Network', 'LBL_RECORD_LABEL', NULL, ARRAY[]::text[]),
  ('Tiến Nguyễn', 'LBL_SONGWRITER', NULL, ARRAY[]::text[]),
  ('MTRI Prod', 'LBL_PRODUCER', NULL, ARRAY[]::text[]),
  ('Chú Gián Nhỏ', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('Youth Music Team', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Tú GG', 'LBL_ARTIST', NULL, ARRAY[]::text[]),
  ('T.Bynz / T Entertainment', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Tóc Tiên', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nguyễn Hữu Liệu', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nhạc Sĩ Phan Long', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('NguyenThuong', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('NT Music', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Diệu Kiên', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('OrchidD', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('NS Nguyễn Phi Hùng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ngô Lan Hương', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Đăng Official', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('LBD Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ben Eagle', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('Pham Hong Bien', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Đình Nguyễn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phan Như Thuỳ', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Le Van Entertainment', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('BIBO Entertainment', 'LBL_PRODUCER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lương Quý Tuấn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('HAPPY BIRTHDAY - TIMMYDZI', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thanh Duy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('SIDUS AND TEU', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('LÊ THU THẢO', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('H2O Ballad', 'LBL_SUB-LABEL', 'CT Media', ARRAY['Nhạc Số']::text[]),
  ('Bconcept Entertainment', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Pin Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('ATOM', 'LBL_PRODUCER', NULL, ARRAY['Nhạc Số']::text[]),
  ('AMY MUSIC', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tấn Tài Entertainment', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('TAN Entertainment', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Beta Music', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('ALIEN.NEXT.DOOR', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Zuongzero Ent', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('UNDERSOUTHERN', 'LBL_RIGHTS_ACQUIRER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phương Mai', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lê Thiện Hiếu', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Dung Hoàng Phạm', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lê Chí Trung', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Vưu Tuấn Kiệt /KIEY', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Saka Trương Tuyền', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lê Thành Trung', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('HANA CẨM TIÊN', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Archived', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('1967 Entertainment', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phạm Thu Hà', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Củ Cải', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('The United Saigon Orchestra', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Brother A', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('LQ MEDIA', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Khả Hiệp Official', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Keyo', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Anna Trâm', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('VietEnt / Âm Nhạc Số', 'LBL_SUB-LABEL', 'ANS Music and Entertainment', ARRAY['Nhạc Số']::text[]),
  ('RayO', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('meChill', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hạo Thiên', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hải Gokume', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('THE GENUINE RECORD', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Xám', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nam Việt - Nhạc Pro', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('BM Music', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('BÌN', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Overline Vietnam', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ngô Quang Dũng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Gia Huy Singer', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tuki Team', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Thái Hoàng', 'LBL_PRODUCER', NULL, ARRAY['Nhạc Số']::text[]),
  ('NSUT Thanh Hằng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('HT PRODUCTIONS', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Châu Dương', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('BIG Records', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Wood Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hồng Quân WyTy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('HỘI', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('NH Music Group', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('VNStudiomusic', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Son Mach', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Satch999', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('RebelSaint Records', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phong Max', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hồ Quang Hiếu', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Đình Dũng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Express Music', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('VT Media', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Seveni Records', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ngô Hồng Quang', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Jay Đào', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('HUVA Music', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thiên Ca', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Quang Dung', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nguyễn Thuý Hà (Nguyên Hà)', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('MAD Production', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Dizzy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Dani D', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Võ Lê Mi', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Meow Label', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Đại Thành', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Cố NSUT QUÝ BÌNH', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Triệu Hồng Ngọc', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thái Chi', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Star Melody', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Mai Tien Dung', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Mega Gs', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Luân', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hivane', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Cộng Hưởng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trung Ngon', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Elbi Original', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('TRANG CHUYÊN OFFICIAL', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Theanh28', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('OG Entertainment', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số','Youtube','Publishing']::text[]),
  ('Như Ngọc', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ngô Lan Hương - Exclusively Licensed to VIEENT', 'LBL_SUB-LABEL', 'Ngô Lan Hương', ARRAY['Nhạc Số']::text[]),
  ('Lê Xuân Nghi', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Khỉ Con Music', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('KC Media', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hữu Công', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Finn Nguyên Hy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('WM Records', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Vũ Hữu Minh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Út Nhị Mino', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tiến Tới Music', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('ROBI', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('PhuongThao', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('PHỤNG QUỐC GIANG', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nguyên Trung', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('ĐÀO NGỌC SANG', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('CHANGMIE', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('BMKTCR', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('AnhVu Music', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Zang', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Mivi Diễm Anh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hào JK', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Đặng Khánh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Duy Hải', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('2!MUCH', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('VŨ PHƯƠNG', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tuệ Phương', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trương Trần Anh Duy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trần Hoài Thy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('SOHASG Sound', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('Shen Music', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ngọc Xuyên', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('N.', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Kem Baby', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hauxenz', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Cwhite', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('135Band', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('TK Records', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('THE EIGHT ENTERTAINMENT', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thảo Phạm', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tân Nhàn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Oliu', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('NH4T Music', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Linh Lor', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Đinh Đại Vũ', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Duuyen', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Do Music', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Win Entertainment', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('VPS', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Vera Madsen', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('UniFLOWs Label', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tuyết Mai', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trương Diễm', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thái Hưng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Synz K', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Reyvin', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('QUÁCH PHÚ THÀNH', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ngô Thái Bảo', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Longg', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('La Hồng Đức', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Jee Trần', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('INZ Entertainment', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Học Sinh Cá Biệt', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('DouMs', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ái Phương', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trọng Nhân', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thiên Dũng', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Quach Tuan Du', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phát Huy T4', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('OGB GANGZ', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Now Or Later', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Non Khăn Rằn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lisa Thùy Lâm', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('La Zung', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Khánh Cường', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Di Di', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Cộng Em', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Célyn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Bùi Vĩnh Phúc', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoài My', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Vết Xước', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trần Ngọc Hân', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thành Sơn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nguyễn Minh Xuân Ái', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Mee Media', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Marse', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lê Vũ Official', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('JBEE7', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hunter V Entertainment', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Y Nhung', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hải Linh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('GLG', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Dreamwork', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('DJ KIM CHOL', 'LBL_PRODUCER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Choco Trúc Phương', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Bình Gold', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('30 Pictures', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('WM20', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('VNDMC', 'LBL_RIGHTS_ACQUIRER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Việt Sơn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('ThiSax', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('The Mars Party', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thắng Rừng Media', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Poorboy', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phát Hồ', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('NHV Entertainment', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nhạc sĩ Nguyễn Thanh Lộc', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Khánh Linh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Cao Trung Hiếu', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Bùi Dương Thái Hà', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('KOY Records', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Đinh Tú', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Vũ Sam', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Võ Minh Lâm', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tuyết Ngân', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thiên Minh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Teddy Tran', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('tạo mới nè122', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('SA', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nguyễn Vĩ', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('NamDuc Official', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Meme Media', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Kim Trọng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('KIỀU THƠ MELLOW', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Kenjumboy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Huy Diệc', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Huấn Hoa Hồng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('HS Talent', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Thiên Đỉnh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Ngọc Sơn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Kaylee', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('h0n', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Gia Linh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('EEZO', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('DIỆU VÂN', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('DG Team', 'LBL_PRODUCER', NULL, ARRAY['Nhạc Số']::text[]),
  ('DAQUIN', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Chuchu', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Anfang', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('9NOTE RECORDS', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('Win G', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Wanbi Tuấn Anh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('VINHTRAN', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Vicky Nhung', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trương Thảo Nhi', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('The SGM Label', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('The 199x', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Rich Khwam', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Pickle Sun', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phú Hunter', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('OCEANS Music Group', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nhạc Sĩ Võ Hiếu', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nhã', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nguyễn Hoàng Phúc', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nathan Lee', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('MUSICTAB', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('MTB Media', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('MINGJI', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('KxK', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('KProx', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ken Trần', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('JAYEO', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Jannc', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('HepiHepi', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('HChun', 'LBL_PRODUCER', NULL, ARRAY['Nhạc Số']::text[]),
  ('GreenD', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Gia Huy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Đỗ Thụy Khanh', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Chí Thiện', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Candy Juice Music', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ca sĩ Phúc Anh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Bin Yet', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('AREA70', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Yoon Nguyên', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('William Music Group', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('VieEnt on behalf of Lemese and Fillinus', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('VGEE', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trương Khải Minh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trini Trinh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trần Việt Dương', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thanh Hưng', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tân Test', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('SynthEX Records', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('STG Music', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Starry Night', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('SoundGanG', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('SONICK OFFICIAL', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Sinl', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Say You Do', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('RIO SUN', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Revir Quang Hà', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Quang Music', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phùng Ngọc Huy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phạm Thu Trang Official', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phạm Thanh Sang', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phạm Quỳnh Như', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nhóm nhạc SOLPA', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('NHÂN DẠNG', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nhạc Sĩ Duy Cường', 'LBL_SONGWRITER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ngân Nara', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('N.O.M', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('My Everything', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('MSV Group', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('Moz Entertainment', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('Mai Yến Chi', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lục Huy', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Long Ngô', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('⁠LIÊU VINH PHÚ - FU', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Khong Anh Music', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Khải Nguyễn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Jesse JP', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Huy Nam', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hồ Phong An', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Homie On Da Mic', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Lan', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hannie', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('H-Kray', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Finn', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Đức Thoa', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('ĐẠT MAX', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('DinhLong', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Diêu Ngọc Bích Trâm', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Dấu Vân Tay', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Cao Sĩ Hùng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('BMD', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('BLUEBELLS STUDIOS', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('Barry Nam Bảo', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Bảo Trân Gemini official', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('B:OKEH', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Astronaut Music Group', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Aplus84', 'LBL_RIGHTS_ACQUIRER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Anh Quân Idol', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Akira Phan', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Air Media', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tấn Thành', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Noisy Boy', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  ('Yeah1', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('X2X Entertainment', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('WowU Media', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('Woni', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Vũ Anh Thư', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('VNDJM', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('VIOLIXX', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Vĩnh Thích Ăn Ngon', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('VieEnt on behalf of Quách Tuấn Du', 'LBL_SUB-LABEL', 'Quach Tuan Du', ARRAY['Nhạc Số']::text[]),
  ('VieEnt on behalf of Nguyên', 'LBL_SUB-LABEL', 'NGUYÊN', ARRAY['Nhạc Số']::text[]),
  ('Vạch Kẻ Đường', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tukie', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('TUDUCA', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tú Tri', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trường Anh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trịnh Thiên Ân', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Trí Vũ', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Tô Đạt', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('TiTi', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Thiên Long', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('THE.B', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('TAP Music', 'LBL_PRODUCER', NULL, ARRAY['Nhạc Số']::text[]),
  ('SSay Huỳnh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Shine By Sai', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('SG CO.OP', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('Sea Media', 'LBL_PRODUCER', NULL, ARRAY['Nhạc Số']::text[]),
  ('RPT NASTEE', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Rion Trung Hiếu', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Ra-Hbie', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('QuocDat', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Poll Official', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Pittu Quyên', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phan Lê Hà My', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phạm Thuỳ Linh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Phạm Thiêng Ngân', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Pha Lê', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('ODDS.TONES Records', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nio Tuấn Dũng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nien', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('NH4T', 'LBL_PRODUCER', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nguyễn Kiều Oanh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nguyễn Cảnh Luân', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('NGUYÊN', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Neam', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nam Lê', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Nam Anh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Một Con Đường Hai Ngã Rẽ', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('MINA THANH TÂM', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Mikayni', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('M - NGUYỄN VĂN NAM', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lightin', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lê Quốc Anh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Lâm Thành Vinh', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('LÂM SUNG', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Láo Soái Nhi', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('LANY S', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Kim Thành Lộc', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Khang Ki', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Khả Ngân', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Javon', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Integral Silence', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('ICG Media', 'LBL_RECORD_LABEL', NULL, ARRAY['Nhạc Số']::text[]),
  ('I''m In Love', 'LBL_INTERNAL', NULL, ARRAY['Nhạc Số']::text[]),
  ('Huyền Anh Yoko', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Huy Bui', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hùng Min', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hồ Đá Chà Gươm', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Hải Dương', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hoàng Hạc', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Henry Ngọc Thạch', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Heni', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Hải Nam', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('GRAMMY MUSIC VIET NAM', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('GABI Music', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Đường Hưng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Đào Mác', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Duy B', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Drum7', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('dotted.', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Dihoa Media', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Denis Dang', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('DAT', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Dablo Anh Dũng', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('CRIIO', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Công Ty Hùng Hoàng - Huỳnh Quốc Huy', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('Chủ Quán Hội', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Châu Dương - Exclusively Licensed to VIEENT', 'LBL_SUB-LABEL', 'Châu Dương', ARRAY['Nhạc Số']::text[]),
  ('Cá Mây', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Bull', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Bùi Thế Bảo Official', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Big Dreams Label', 'LBL_ARTIST_MANAGEMENT', NULL, ARRAY['Nhạc Số']::text[]),
  ('BI BẢO', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Bee9 Offical', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('ASC', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Annie Thai', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('ALIEN.NEXT.DOOR - EXCLUSIVE LICENSED TO VIEENT', 'LBL_SUB-LABEL', 'ALIEN.NEXT.DOOR', ARRAY['Nhạc Số']::text[]),
  ('ACV Entertainment', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('ACB Pictures', 'LBL_MEDIA_ORG', NULL, ARRAY['Nhạc Số']::text[]),
  ('A.N PRODUCTIONS', 'LBL_MUSIC_COMPANY', NULL, ARRAY['Nhạc Số']::text[]),
  ('4thằngngu', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('2kTraDa', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[]),
  ('Soul Music Worldwide', 'LBL_END_CONTRACT', NULL, ARRAY[]::text[]),
  (':B', 'LBL_ARTIST', NULL, ARRAY['Nhạc Số']::text[])
)
update labels l
set
  default_lbl_tag = coalesce(l.default_lbl_tag, d.lbl_tag),
  parent_label = coalesce(l.parent_label, d.parent_label),
  hop_tac = case when l.hop_tac is null or array_length(l.hop_tac, 1) is null then d.hop_tac else l.hop_tac end
from import_data d
where l.label_name = d.csv_name or l.label_name = 'HĐ - ' || d.csv_name;
