-- SUPERSEDED — do not run this file. It turned out not to fully apply in
-- practice (releases.subteam_tags_locked ended up missing), and it's now
-- also out of date (round 264 retired the `subteams` table entirely).
--
-- Run sql/pending/add-round264-consolidated-subteam-migration.sql
-- instead — it does everything this file was meant to, safely, no matter
-- what already did or didn't apply.
