-- Round 262 — "2 fix" request. Two things:
--
-- 1. New `subteams` reference table (team_name, subteam_name, note),
--    managed from a new dev-only Config tab (SUBTEAM). This replaces the
--    Round 261 free-text profiles.subteam field's "no fixed list on
--    purpose" approach with a real, curated list — and Youtube/
--    Publishing/Operation stop being standalone assignable segments,
--    folding back into a single "OPS" segment with their old value
--    moved onto profiles.subteam instead (reversing Round 30's split,
--    per explicit request: "remove the operations, youtube and
--    publishing (those became subteam of the current OPS)").
--
-- 2. Marketing's INDIE/VPOP/ENVI/VIEENT project tags (Round 258/260,
--    releases.project_tag / project_tag_locked — a single cycling value)
--    are reconceived as 4 independent is_subteam booleans, same shape as
--    Round 261's subteam_tags jsonb map. This migration folds any
--    existing project_tag data into subteam_tags so nothing is lost, and
--    adds subteam_tags_locked (mirrors project_tag_locked's "don't
--    re-auto-flag after a manual change" semantics, per-subteam instead
--    of a single flag). project_tag / project_tag_locked columns are
--    left in place, unused, rather than dropped — see the app code
--    comments in app/releases/page.js and app/releases/[id]/page.js for
--    where the cycling UI was removed.

create table if not exists subteams (
  id bigint generated by default as identity primary key,
  team_name text not null,
  subteam_name text not null,
  note text,
  created_at timestamptz not null default now(),
  unique (team_name, subteam_name)
);

-- Seed: OPS's 3 former standalone segments, and Marketing's 4 tag values
-- (both sets already had real meaning in the app before this round).
insert into subteams (team_name, subteam_name, note)
values
  ('OPS', 'Youtube', 'Was its own segment before Round 262.'),
  ('OPS', 'Publishing', 'Was its own segment before Round 262.'),
  ('OPS', 'Operation', 'Was its own segment before Round 262.'),
  ('Marketing', 'INDIE', 'Round 258/260 project tag, now a subteam tag.'),
  ('Marketing', 'VPOP', 'Round 260 project tag, now a subteam tag.'),
  ('Marketing', 'ENVI', 'Round 260 project tag, now a subteam tag.'),
  ('Marketing', 'VIEENT', 'Round 260 project tag, now a subteam tag.')
on conflict (team_name, subteam_name) do nothing;

-- Migrate profiles: anyone on one of the 3 old OPS sub-team segments
-- moves to segment="OPS" with their old segment value preserved as their
-- subteam (only where they didn't already have a subteam set manually).
update profiles
set subteam = coalesce(subteam, segment), segment = 'OPS'
where segment in ('Youtube', 'Publishing', 'Operation');

-- Marketing's 4-tag rework: fold any existing project_tag into
-- subteam_tags, and add the matching lock map.
alter table releases add column if not exists subteam_tags_locked jsonb not null default '{}'::jsonb;

update releases
set
  subteam_tags = subteam_tags || jsonb_build_object(project_tag, true),
  subteam_tags_locked = subteam_tags_locked || jsonb_build_object(project_tag, true)
where project_tag is not null;
